Fixed Py3.13 pydantic serialization (#293)
## What caused the regression?

In 3.13
```py
issubclass(typing.Annotated, str)
Traceback (most recent call last):
  File "<python-input-3>", line 1, in <module>
    issubclass(typing.Annotated, str)
    ~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
TypeError: issubclass() arg 1 must be a class
>>> isinstance(typing.Annotated, type)
False
```

In 3.10
```py
>>> issubclass(typing.Annotated, str)
False
>>> isinstance(typing.Annotated, type)
True
```

This broke our handling of Annotated types.